# Generated by Django 4.2.5 on 2023-09-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Сategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=50)),
                ('lot_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lot_quantity', models.ImageField(upload_to='')),
                ('lot_comment', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tradesave.сategory')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tradesave.status')),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tradesave.types')),
            ],
        ),
    ]
